/* eslint-disable @next/next/no-sync-scripts */
import React from 'react'

interface Props {

}

const CustomerHeader = (props: Props) => {
    return (
        <>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://unpkg.com/primeicons/primeicons.css" />
            <link rel="stylesheet" href="https://unpkg.com/primereact/resources/themes/lara-light-indigo/theme.css" />
            <link rel="stylesheet" href="https://unpkg.com/primereact/resources/primereact.min.css" />
            <link rel="stylesheet" href="https://unpkg.com/primeflex@2.0.0/primeflex.min.css" />
            <script src="https://unpkg.com/react/umd/react.production.min.js"></script>
            <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
            <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
            <script src="https://unpkg.com/react-transition-group@4.4.2/dist/react-transition-group.js"></script>
            <script src="https://unpkg.com/primereact/core/core.min.js"></script>
            <script src="https://unpkg.com/primereact/primereact.all.min.js"></script>
        </>
    )
}

export default CustomerHeader
